import { render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import AssetPassportPage from '../AssetPassportPage'

// ─── Mock apiClient ──────────────────────────────────────────────────

const MOCK_PASSPORT_COMPLIANT = {
  asset: {
    id: 'asset-1',
    name: 'Plynový kotel A',
    category: 'tzb',
    status: 'aktivni',
    assetTypeId: 'at-1',
    assetType: { id: 'at-1', name: 'Plynový kotel', code: 'KOTEL_PLYN', _count: { activityAssignments: 2 } },
    manufacturer: 'Buderus',
    model: 'Logamax U072',
    serialNumber: 'SN-12345',
    location: 'Kotelna',
    property: { id: 'p1', name: 'Objekt Praha 1' },
    unit: null,
    purchaseDate: null,
    purchaseValue: null,
    warrantyUntil: null,
    serviceInterval: 365,
    lastServiceDate: null,
    nextServiceDate: null,
    notes: 'Kotel pro centrální vytápění',
    serviceRecords: [],
    propertyId: 'p1',
    unitId: null,
    deletedAt: null,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    _count: { serviceRecords: 0 },
  },
  compliance: {
    status: 'compliant',
    totalPlans: 2,
    activePlans: 2,
    overduePlans: 0,
    dueSoonPlans: 0,
    missingMandatoryPlans: 0,
    lastRevisionAt: '2025-12-01T10:00:00Z',
    nextDueAt: '2026-06-01T10:00:00Z',
  },
  plansSummary: {
    total: 2,
    autoGenerated: 2,
    customized: 0,
    overdue: 0,
    dueSoon: 0,
  },
  latestRevision: {
    id: 'ev-1',
    revisionTypeName: 'Servis kotle',
    performedAt: '2025-12-01T10:00:00Z',
    resultStatus: 'passed',
  },
  nextDue: {
    revisionPlanId: 'rp-1',
    revisionTypeName: 'Kontrola spalin',
    dueAt: '2026-06-01T10:00:00Z',
    daysUntil: 79,
  },
}

const MOCK_PASSPORT_NO_TYPE = {
  asset: {
    ...MOCK_PASSPORT_COMPLIANT.asset,
    id: 'asset-2',
    name: 'Neidentifikované zařízení',
    assetTypeId: null,
    assetType: null,
  },
  compliance: {
    status: 'not_configured',
    totalPlans: 0,
    activePlans: 0,
    overduePlans: 0,
    dueSoonPlans: 0,
    missingMandatoryPlans: 0,
    lastRevisionAt: null,
    nextDueAt: null,
  },
  plansSummary: { total: 0, autoGenerated: 0, customized: 0, overdue: 0, dueSoon: 0 },
  latestRevision: null,
  nextDue: null,
}

const MOCK_PASSPORT_OVERDUE = {
  ...MOCK_PASSPORT_COMPLIANT,
  compliance: {
    ...MOCK_PASSPORT_COMPLIANT.compliance,
    status: 'overdue',
    overduePlans: 1,
  },
  plansSummary: { ...MOCK_PASSPORT_COMPLIANT.plansSummary, overdue: 1 },
}

let mockPassport = MOCK_PASSPORT_COMPLIANT as any

vi.mock('../../../core/api/client', () => ({
  apiClient: {
    get: vi.fn((url: string) => {
      if (url.includes('/passport')) return Promise.resolve({ data: mockPassport })
      if (url.includes('/revisions/plans')) return Promise.resolve({ data: { data: [], total: 0 } })
      if (url.includes('/revision-history')) return Promise.resolve({ data: { data: [], total: 0 } })
      if (url.includes('/documents')) return Promise.resolve({ data: { data: [], total: 0 } })
      if (url.includes('/audit-events')) return Promise.resolve({ data: { data: [], total: 0 } })
      return Promise.resolve({ data: {} })
    }),
    post: vi.fn(() => Promise.resolve({ data: { created: 0, skipped: 1, skippedCustomized: 0 } })),
  },
}))

function renderPassport(assetId = 'asset-1') {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={qc}>
      <MemoryRouter initialEntries={[`/assets/${assetId}`]}>
        <Routes>
          <Route path="/assets/:id" element={<AssetPassportPage />} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>,
  )
}

describe('AssetPassportPage', () => {
  beforeEach(() => {
    mockPassport = MOCK_PASSPORT_COMPLIANT
  })

  it('renders asset name in header', async () => {
    renderPassport()
    expect(await screen.findByText('Plynový kotel A')).toBeTruthy()
  })

  it('renders asset type badge', async () => {
    renderPassport()
    expect(await screen.findByText('Plynový kotel')).toBeTruthy()
  })

  it('renders compliance status as compliant', async () => {
    renderPassport()
    expect(await screen.findByText('V pořádku')).toBeTruthy()
  })

  it('renders tab navigation', async () => {
    renderPassport()
    await screen.findByText('Plynový kotel A')
    // "Revizní plány" appears in both tab and overview section, so use getAllByText
    expect(screen.getAllByText('Přehled').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('Plán činností').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('Historie').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('Dokumenty').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('Změny').length).toBeGreaterThanOrEqual(1)
  })

  it('shows asset without type badge when no assetTypeId', async () => {
    mockPassport = MOCK_PASSPORT_NO_TYPE
    renderPassport('asset-2')
    await screen.findByText('Neidentifikované zařízení')
    expect(screen.getByText('Bez typu zařízení')).toBeTruthy()
    expect(screen.getByText('Není nastaveno')).toBeTruthy()
  })

  it('shows no-asset-type info message when not_configured', async () => {
    mockPassport = MOCK_PASSPORT_NO_TYPE
    renderPassport('asset-2')
    await screen.findByText('Neidentifikované zařízení')
    expect(screen.getByText(/automatická synchronizace plánů není k dispozici/i)).toBeTruthy()
  })

  it('shows overdue banner when plans are overdue', async () => {
    mockPassport = MOCK_PASSPORT_OVERDUE
    renderPassport()
    await screen.findByText('Plynový kotel A')
    expect(screen.getByText(/po termínu/i, { selector: 'strong' })).toBeTruthy()
  })

  it('shows Po termínu! badge in header when overdue', async () => {
    mockPassport = MOCK_PASSPORT_OVERDUE
    renderPassport()
    await screen.findByText('Po termínu')
    expect(screen.getByText('Po termínu')).toBeTruthy()
  })

  it('renders overview tab with technical details by default', async () => {
    renderPassport()
    await screen.findByText('Plynový kotel A')
    expect(screen.getByText('Technické údaje')).toBeTruthy()
  })

  it('renders latest revision info in overview tab', async () => {
    renderPassport()
    await screen.findByText('Plynový kotel A')
    expect(screen.getByText('Servis kotle')).toBeTruthy()
  })

  it('renders next due info in overview tab', async () => {
    renderPassport()
    await screen.findByText('Plynový kotel A')
    expect(screen.getByText('Kontrola spalin')).toBeTruthy()
  })

  it('renders serial number when present', async () => {
    renderPassport()
    await screen.findByText('S/N: SN-12345')
  })
})
