import { useState, lazy, Suspense } from 'react'
import { useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  ArrowLeft, CheckCircle, AlertTriangle, XCircle, MinusCircle,
  ClipboardList, History, FileText, Activity, RefreshCw,
  CalendarClock, Clock, ScrollText,
} from 'lucide-react'
import {
  Badge, Button, LoadingState, ErrorState, KpiCard, Table,
} from '../../shared/components'
import type { BadgeVariant, Column } from '../../shared/components'
import { apiClient } from '../../core/api/client'
import type { Asset } from './AssetListPage'
import { useFieldChecks } from '../field-checks/api/field-checks.queries'
import type { FieldCheckItem, FieldCheckConfidenceLevel } from '../field-checks/api/field-checks.api'

const FieldCheckModal = lazy(() => import('../field-checks/FieldCheckModal'))

// ─── Types ─────────────────────────────────────────────────────────

type AssetComplianceStatus = 'not_configured' | 'missing_plan' | 'overdue' | 'due_soon' | 'compliant'

interface PassportResponse {
  asset: Asset & { serviceRecords: ServiceRecord[] }
  compliance: {
    status: AssetComplianceStatus
    totalPlans: number
    activePlans: number
    overduePlans: number
    dueSoonPlans: number
    missingMandatoryPlans: number
    lastRevisionAt: string | null
    nextDueAt: string | null
  }
  plansSummary: {
    total: number
    autoGenerated: number
    customized: number
    overdue: number
    dueSoon: number
  }
  latestRevision: {
    id: string
    revisionTypeName: string
    performedAt: string
    resultStatus: string | null
  } | null
  nextDue: {
    revisionPlanId: string
    revisionTypeName: string
    dueAt: string
    daysUntil: number
  } | null
}

interface RevisionHistoryItem {
  id: string
  performedAt: string | null
  scheduledAt: string | null
  resultStatus: string | null
  summary: string | null
  vendorName: string | null
  performedBy: string | null
  revisionPlan: {
    id: string; title: string
    revisionType: { id: string; name: string; code: string }
  }
}

interface AuditEvent {
  id: string
  action: string
  entity: string
  entityId: string | null
  createdAt: string
  user: { id: string; name: string; email: string } | null
}

interface RevisionPlan {
  id: string
  title: string
  intervalDays: number
  nextDueAt: string | null
  status: string
  complianceStatus?: string
  generatedFromAssetType?: boolean
  isCustomized?: boolean
  isMandatory?: boolean
  revisionType?: { id: string; name: string; code: string }
}

interface SyncPreviewItem {
  revisionTypeId: string
  name: string
  code: string
  effectiveIntervalDays: number
  isRequired: boolean
  action: 'create' | 'skip_exists' | 'skip_customized'
  existingPlanIsCustomized: boolean
}

interface ServiceRecord {
  id: string
  date: string
  type: string
  description: string | null
  cost: number | null
  supplier: string | null
}

// ─── Constants ──────────────────────────────────────────────────────

const RESULT_LABEL: Record<string, string> = {
  passed: 'Vyhovující', passed_with_notes: 'S poznámkami',
  failed: 'Nevyhovující', cancelled: 'Zrušeno', planned: 'Plánováno',
}
const RESULT_COLOR: Record<string, BadgeVariant> = {
  passed: 'green', passed_with_notes: 'yellow', failed: 'red',
  cancelled: 'muted', planned: 'blue',
}
const COMPLIANCE_LABEL: Record<string, string> = {
  compliant: 'V pořádku', due_soon: 'Blíží se', overdue: 'Po termínu',
  overdue_critical: 'Kritické', performed_pending_protocol: 'Bez protokolu',
  performed_pending_signature: 'Čeká podpis', performed_unconfirmed: 'Nepotvrzeno',
}
const COMPLIANCE_COLOR: Record<string, BadgeVariant> = {
  compliant: 'green', due_soon: 'yellow', overdue: 'red', overdue_critical: 'red',
  performed_pending_protocol: 'yellow', performed_pending_signature: 'yellow',
  performed_unconfirmed: 'muted',
}
const CATEGORY_LABEL: Record<string, string> = {
  tzb: 'TZB', stroje: 'Stroje', vybaveni: 'Vybavení',
  vozidla: 'Vozidla', it: 'IT', ostatni: 'Ostatní',
}
const STATUS_LABEL: Record<string, string> = {
  aktivni: 'Aktivní', servis: 'V servisu', vyrazeno: 'Vyřazeno', neaktivni: 'Neaktivní',
}
const STATUS_COLOR: Record<string, BadgeVariant> = {
  aktivni: 'green', servis: 'yellow', vyrazeno: 'red', neaktivni: 'muted',
}

const TABS = [
  { id: 'overview', label: 'Přehled', icon: <Activity size={14} /> },
  { id: 'plans', label: 'Plán činností', icon: <ClipboardList size={14} /> },
  { id: 'history', label: 'Historie', icon: <History size={14} /> },
  { id: 'checks', label: 'Kontroly', icon: <CheckCircle size={14} /> },
  { id: 'documents', label: 'Dokumenty', icon: <FileText size={14} /> },
  { id: 'audit', label: 'Změny', icon: <ScrollText size={14} /> },
]

const CONFIDENCE_LABEL: Record<FieldCheckConfidenceLevel, string> = {
  low: 'Nízká', medium: 'Střední', high: 'Vysoká',
}
const CONFIDENCE_COLOR: Record<FieldCheckConfidenceLevel, BadgeVariant> = {
  low: 'yellow', medium: 'blue', high: 'green',
}
const CHECK_RESULT_LABEL: Record<string, string> = {
  ok: 'V pořádku', issue_found: 'Závada', needs_follow_up: 'Sledovat', not_accessible: 'Nepřístupné',
}
const CHECK_RESULT_COLOR: Record<string, BadgeVariant> = {
  ok: 'green', issue_found: 'red', needs_follow_up: 'yellow', not_accessible: 'muted',
}

// ─── Compliance Header Badge ─────────────────────────────────────────

function ComplianceHeaderBadge({ status }: { status: AssetComplianceStatus }) {
  const cfg: Record<AssetComplianceStatus, { icon: React.ReactNode; label: string; color: string }> = {
    compliant: { icon: <CheckCircle size={16} />, label: 'V pořádku', color: 'var(--success, #22c55e)' },
    due_soon: { icon: <AlertTriangle size={16} />, label: 'Blíží se termín', color: 'var(--accent-orange, #f59e0b)' },
    overdue: { icon: <XCircle size={16} />, label: 'Po termínu', color: 'var(--danger, #ef4444)' },
    missing_plan: { icon: <AlertTriangle size={16} />, label: 'Chybí plán činností', color: 'var(--accent-orange, #f59e0b)' },
    not_configured: { icon: <MinusCircle size={16} />, label: 'Není nastaveno', color: 'var(--text-muted)' },
  }
  const c = cfg[status]
  return (
    <span style={{ display: 'flex', alignItems: 'center', gap: 6, color: c.color, fontWeight: 600, fontSize: '0.9rem' }}>
      {c.icon} {c.label}
    </span>
  )
}

// ─── Overdue Banner ──────────────────────────────────────────────────

function OverdueBanner({ count }: { count: number }) {
  if (count === 0) return null
  return (
    <div style={{
      background: 'var(--danger-bg, #fef2f2)', border: '1px solid var(--danger, #ef4444)',
      borderRadius: 8, padding: '10px 16px', marginBottom: 16,
      display: 'flex', alignItems: 'center', gap: 10, color: 'var(--danger, #ef4444)',
    }}>
      <XCircle size={18} />
      <strong>{count} {count === 1 ? 'plán činností je' : 'plány činností jsou'} po termínu.</strong>
      <span style={{ fontSize: '0.85rem' }}>Zkontrolujte záložku Plán činností.</span>
    </div>
  )
}

// ─── Sync Panel ───────────────────────────────────────────────────────

function SyncPanel({ assetId }: { assetId: string }) {
  const qc = useQueryClient()
  const [showPreview, setShowPreview] = useState(false)
  const [syncResult, setSyncResult] = useState<{ created: number; skipped: number; skippedCustomized: number } | null>(null)

  const previewQ = useQuery<SyncPreviewItem[]>({
    queryKey: ['assets', assetId, 'sync-preview'],
    queryFn: () => apiClient.get(`/assets/${assetId}/sync-plans/preview`).then((r) => r.data),
    enabled: showPreview,
    staleTime: 0,
  })

  const syncMut = useMutation({
    mutationFn: () => apiClient.post(`/assets/${assetId}/sync-plans`, { skipCustomized: true }).then((r) => r.data),
    onSuccess: (data) => {
      setSyncResult(data)
      qc.invalidateQueries({ queryKey: ['assets', assetId] })
      qc.invalidateQueries({ queryKey: ['revisions'] })
    },
  })

  const toCreate = previewQ.data?.filter((i) => i.action === 'create').length ?? 0

  return (
    <div style={{ border: '1px solid var(--border)', borderRadius: 10, padding: 16, marginBottom: 20 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: showPreview ? 12 : 0 }}>
        <div>
          <span style={{ fontWeight: 700, fontSize: '0.9rem' }}>Synchronizace plánů z typu zařízení</span>
          {syncResult && (
            <span style={{ marginLeft: 12, fontSize: '0.85rem', color: 'var(--success, #22c55e)' }}>
              Vytvořeno: {syncResult.created}, přeskočeno: {syncResult.skipped + syncResult.skippedCustomized}
            </span>
          )}
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Button size="sm" onClick={() => { setShowPreview((p) => !p); setSyncResult(null) }}>
            {showPreview ? 'Skrýt náhled' : 'Zkontrolovat'}
          </Button>
          {showPreview && toCreate > 0 && (
            <Button
              size="sm"
              variant="primary"
              disabled={syncMut.isPending}
              onClick={() => syncMut.mutate()}
              icon={syncMut.isPending ? <RefreshCw size={13} className="spin" /> : undefined}
            >
              {syncMut.isPending ? 'Synchronizuji...' : `Vytvořit ${toCreate} plánů`}
            </Button>
          )}
        </div>
      </div>

      {showPreview && (
        <div>
          {previewQ.isLoading && <LoadingState />}
          {previewQ.data && previewQ.data.length === 0 && (
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', margin: 0 }}>Žádné šablony k synchronizaci.</p>
          )}
          {previewQ.data && previewQ.data.length > 0 && (
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border)' }}>
                  <th style={{ textAlign: 'left', padding: '6px 0', color: 'var(--text-muted)', fontWeight: 500 }}>Typ revize</th>
                  <th style={{ textAlign: 'left', padding: '6px 0', color: 'var(--text-muted)', fontWeight: 500 }}>Interval</th>
                  <th style={{ textAlign: 'left', padding: '6px 0', color: 'var(--text-muted)', fontWeight: 500 }}>Povinný</th>
                  <th style={{ textAlign: 'left', padding: '6px 0', color: 'var(--text-muted)', fontWeight: 500 }}>Akce</th>
                </tr>
              </thead>
              <tbody>
                {previewQ.data.map((item) => {
                  const actionBadge: Record<string, { label: string; variant: BadgeVariant }> = {
                    create: { label: 'Vytvořit', variant: 'green' },
                    skip_exists: { label: 'Existuje', variant: 'muted' },
                    skip_customized: { label: 'Upraveno', variant: 'yellow' },
                  }
                  const ab = actionBadge[item.action] ?? { label: item.action, variant: 'muted' }
                  return (
                    <tr key={item.revisionTypeId} style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '7px 0' }}>
                        <span style={{ fontWeight: 600 }}>{item.name}</span>
                        <span style={{ color: 'var(--text-muted)', marginLeft: 6 }}>{item.code}</span>
                      </td>
                      <td style={{ padding: '7px 0' }}>{item.effectiveIntervalDays}d</td>
                      <td style={{ padding: '7px 0' }}>{item.isRequired ? 'Ano' : 'Ne'}</td>
                      <td style={{ padding: '7px 0' }}>
                        <Badge variant={ab.variant as BadgeVariant}>{ab.label}</Badge>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  )
}

// ─── Plans Tab ──────────────────────────────────────────────────────

function PlansTab({ assetId, hasAssetType }: { assetId: string; hasAssetType: boolean }) {
  const { data, isLoading, error } = useQuery<{ data: RevisionPlan[]; total: number }>({
    queryKey: ['assets', assetId, 'plans'],
    queryFn: () => apiClient.get(`/revisions/plans`, { params: { assetId, limit: 50 } }).then((r) => r.data),
  })

  if (isLoading) return <LoadingState />
  if (error || !data) return <ErrorState message="Nepodařilo se načíst plány." />

  const fmtDate = (d: string | null) => d ? new Date(d).toLocaleDateString('cs-CZ') : '—'
  const now = Date.now()

  const columns: Column<RevisionPlan>[] = [
    {
      key: 'title', label: 'Plán',
      render: (p) => (
        <span>
          <span style={{ fontWeight: 600 }}>{p.title}</span>
          {p.isMandatory && <span style={{ marginLeft: 6 }}><Badge variant="red">Povinný</Badge></span>}
          {p.generatedFromAssetType && <span style={{ marginLeft: 4 }}><Badge variant="blue">Auto</Badge></span>}
          {p.isCustomized && <span style={{ marginLeft: 4 }}><Badge variant="yellow">Upraveno</Badge></span>}
        </span>
      ),
    },
    {
      key: 'revisionType', label: 'Typ',
      render: (p) => p.revisionType ? <Badge variant="muted">{p.revisionType.code}</Badge> : '—',
    },
    { key: 'intervalDays', label: 'Interval', render: (p) => `${p.intervalDays}d` },
    {
      key: 'nextDueAt', label: 'Termín',
      render: (p) => {
        if (!p.nextDueAt) return <span className="text-muted">—</span>
        const days = Math.ceil((new Date(p.nextDueAt).getTime() - now) / 86_400_000)
        const color = days < 0 ? 'var(--danger)' : days <= 30 ? 'var(--accent-orange)' : 'var(--text-muted)'
        return (
          <span style={{ color, fontSize: '0.85rem' }}>
            {fmtDate(p.nextDueAt)}
            {days < 0 && <span style={{ marginLeft: 4, fontSize: '0.78rem' }}>({Math.abs(days)}d po termínu)</span>}
          </span>
        )
      },
    },
    {
      key: 'complianceStatus', label: 'Stav',
      render: (p) => p.complianceStatus ? (
        <Badge variant={COMPLIANCE_COLOR[p.complianceStatus] ?? 'muted'}>
          {COMPLIANCE_LABEL[p.complianceStatus] ?? p.complianceStatus}
        </Badge>
      ) : '—',
    },
  ]

  return (
    <div>
      {hasAssetType && <SyncPanel assetId={assetId} />}

      {data.data.length === 0 ? (
        <div style={{
          padding: 24, textAlign: 'center', border: '1px dashed var(--border)',
          borderRadius: 8, color: 'var(--text-muted)',
        }}>
          <ClipboardList size={32} style={{ margin: '0 auto 8px', opacity: 0.4 }} />
          <p style={{ margin: 0, fontWeight: 600 }}>Žádné revizní plány</p>
          {hasAssetType && <p style={{ margin: '4px 0 0', fontSize: '0.85rem' }}>Použijte synchronizaci výše pro vytvoření plánů z typu zařízení.</p>}
        </div>
      ) : (
        <Table data={data.data} columns={columns} rowKey={(p) => p.id} emptyText="Žádné plány" />
      )}
    </div>
  )
}

// ─── History Tab ────────────────────────────────────────────────────

function HistoryTab({ assetId }: { assetId: string }) {
  const { data, isLoading, error } = useQuery<{ data: RevisionHistoryItem[]; total: number }>({
    queryKey: ['assets', assetId, 'revision-history'],
    queryFn: () => apiClient.get(`/assets/${assetId}/revision-history`).then((r) => r.data),
  })

  if (isLoading) return <LoadingState />
  if (error || !data) return <ErrorState message="Nepodařilo se načíst historii." />
  if (data.data.length === 0) return (
    <div style={{ padding: '32px 0', textAlign: 'center', color: 'var(--text-muted)' }}>
      <History size={32} style={{ margin: '0 auto 8px', opacity: 0.4 }} />
      <p style={{ margin: 0 }}>Zatím žádné provedené revize.</p>
    </div>
  )

  const fmtDate = (d: string | null) => d ? new Date(d).toLocaleDateString('cs-CZ') : '—'

  const columns: Column<RevisionHistoryItem>[] = [
    {
      key: 'performedAt', label: 'Datum',
      render: (e) => fmtDate(e.performedAt ?? e.scheduledAt),
    },
    {
      key: 'revisionPlan', label: 'Typ revize',
      render: (e) => (
        <span>
          <span style={{ fontWeight: 600 }}>{e.revisionPlan.revisionType.name}</span>
          <span style={{ color: 'var(--text-muted)', marginLeft: 6, fontSize: '0.82rem' }}>
            {e.revisionPlan.revisionType.code}
          </span>
        </span>
      ),
    },
    {
      key: 'resultStatus', label: 'Výsledek',
      render: (e) => e.resultStatus ? (
        <Badge variant={RESULT_COLOR[e.resultStatus] ?? 'muted'}>
          {RESULT_LABEL[e.resultStatus] ?? e.resultStatus}
        </Badge>
      ) : '—',
    },
    { key: 'vendorName', label: 'Dodavatel', render: (e) => e.vendorName || <span className="text-muted">—</span> },
    {
      key: 'summary', label: 'Poznámka',
      render: (e) => <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>{e.summary || '—'}</span>,
    },
  ]

  return <Table data={data.data} columns={columns} rowKey={(e) => e.id} emptyText="Žádná história" />
}

// ─── Documents Tab ──────────────────────────────────────────────────

function DocumentsTab({ assetId }: { assetId: string }) {
  const { data, isLoading, error } = useQuery({
    queryKey: ['assets', assetId, 'documents'],
    queryFn: () => apiClient.get(`/documents`, { params: { entityType: 'asset', entityId: assetId } }).then((r) => r.data),
  })

  if (isLoading) return <LoadingState />
  if (error) return <ErrorState message="Nepodařilo se načíst dokumenty." />

  const docs: any[] = (data as any)?.data ?? (Array.isArray(data) ? data : [])

  if (docs.length === 0) return (
    <div style={{ padding: '32px 0', textAlign: 'center', color: 'var(--text-muted)' }}>
      <FileText size={32} style={{ margin: '0 auto 8px', opacity: 0.4 }} />
      <p style={{ margin: 0 }}>Žádné dokumenty k tomuto zařízení.</p>
    </div>
  )

  return (
    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
      {docs.map((doc) => (
        <li key={doc.id} style={{
          padding: '10px 14px', border: '1px solid var(--border)',
          borderRadius: 8, display: 'flex', alignItems: 'center', gap: 12,
        }}>
          <FileText size={16} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontWeight: 600, fontSize: '0.9rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {doc.name ?? doc.originalName ?? doc.id}
            </div>
            {doc.createdAt && (
              <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
                {new Date(doc.createdAt).toLocaleDateString('cs-CZ')}
              </div>
            )}
          </div>
          {doc.url && (
            <a href={doc.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: '0.82rem', color: 'var(--accent-blue)' }}>
              Otevřít
            </a>
          )}
        </li>
      ))}
    </ul>
  )
}

// ─── Audit Tab ───────────────────────────────────────────────────────

function AuditTab({ assetId }: { assetId: string }) {
  const { data, isLoading, error } = useQuery<{ data: AuditEvent[]; total: number }>({
    queryKey: ['assets', assetId, 'audit'],
    queryFn: () => apiClient.get(`/assets/${assetId}/audit-events`).then((r) => r.data),
  })

  if (isLoading) return <LoadingState />
  if (error || !data) return <ErrorState message="Nepodařilo se načíst audit." />
  if (data.data.length === 0) return (
    <p style={{ color: 'var(--text-muted)', padding: '24px 0' }}>Žádné audit záznamy.</p>
  )

  return (
    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 6 }}>
      {data.data.map((ev) => (
        <li key={ev.id} style={{
          padding: '10px 14px', borderLeft: '3px solid var(--border)',
          display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12,
        }}>
          <div>
            <span style={{ fontWeight: 600, fontSize: '0.85rem' }}>{ev.action}</span>
            {ev.user && (
              <span style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginLeft: 8 }}>
                {ev.user.name}
              </span>
            )}
          </div>
          <span style={{ color: 'var(--text-muted)', fontSize: '0.8rem', flexShrink: 0 }}>
            {new Date(ev.createdAt).toLocaleString('cs-CZ')}
          </span>
        </li>
      ))}
    </ul>
  )
}

// ─── Overview Tab ────────────────────────────────────────────────────

function OverviewTab({ passport }: { passport: PassportResponse }) {
  const { asset, compliance, latestRevision, nextDue, plansSummary } = passport
  const fmtDate = (d: string | null | undefined) => d ? new Date(d).toLocaleDateString('cs-CZ') : '—'
  const fmtMoney = (v: number | null) => v !== null ? `${v.toLocaleString('cs-CZ')} Kč` : '—'

  const rows: [string, string][] = [
    ['Kategorie', CATEGORY_LABEL[asset.category] ?? asset.category],
    ['Stav', STATUS_LABEL[asset.status] ?? asset.status],
    ['Výrobce', asset.manufacturer ?? '—'],
    ['Model', asset.model ?? '—'],
    ['Sériové číslo', asset.serialNumber ?? '—'],
    ['Umístění', asset.location ?? '—'],
    ['Nemovitost', asset.property?.name ?? '—'],
    ['Jednotka', asset.unit?.name ?? '—'],
    ['Datum nákupu', fmtDate(asset.purchaseDate)],
    ['Pořizovací hodnota', fmtMoney(asset.purchaseValue)],
    ['Záruka do', fmtDate(asset.warrantyUntil)],
    ['Interval servisu', asset.serviceInterval ? `${asset.serviceInterval} dní` : '—'],
  ]

  const cardStyle = { padding: 16, border: '1px solid var(--border)', borderRadius: 10 }
  const sectionTitle = {
    fontSize: '0.82rem', fontWeight: 700, marginBottom: 12,
    textTransform: 'uppercase' as const, color: 'var(--text-muted)', letterSpacing: '0.05em',
  }

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, alignItems: 'start' }}>
      {/* Left: technical details */}
      <div>
        <p style={sectionTitle}>Technické údaje</p>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <tbody>
            {rows.map(([label, value]) => (
              <tr key={label} style={{ borderBottom: '1px solid var(--border)' }}>
                <td style={{ padding: '7px 0', color: 'var(--text-muted)', fontSize: '0.85rem', width: '45%' }}>{label}</td>
                <td style={{ padding: '7px 0', fontSize: '0.9rem', fontWeight: 500 }}>{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {asset.notes && (
          <div style={{ marginTop: 16, padding: 12, background: 'var(--surface-alt, var(--surface))', borderRadius: 8 }}>
            <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)' }}>Poznámky</p>
            <p style={{ margin: '4px 0 0', fontSize: '0.9rem' }}>{asset.notes}</p>
          </div>
        )}
      </div>

      {/* Right: compliance + revision summary */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {/* Compliance kpi */}
        <div style={cardStyle}>
          <p style={sectionTitle}>Revizní plány</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 8, marginBottom: 12 }}>
            <KpiCard label="Celkem" value={String(plansSummary.total)} color="var(--accent-blue)" />
            <KpiCard label="Po termínu" value={String(plansSummary.overdue)} color="var(--danger, #ef4444)" />
            <KpiCard label="Blíží se" value={String(plansSummary.dueSoon)} color="var(--accent-orange, #f59e0b)" />
          </div>
          {plansSummary.total > 0 && (
            <div style={{ display: 'flex', gap: 12, fontSize: '0.82rem', color: 'var(--text-muted)' }}>
              <span>Auto: {plansSummary.autoGenerated}</span>
              {plansSummary.customized > 0 && <span>Upraveno: {plansSummary.customized}</span>}
            </div>
          )}
          {compliance.missingMandatoryPlans > 0 && (
            <div style={{ marginTop: 10, fontSize: '0.85rem', color: 'var(--accent-orange, #f59e0b)', display: 'flex', alignItems: 'center', gap: 6 }}>
              <AlertTriangle size={14} />
              Chybí {compliance.missingMandatoryPlans} povinných plánů
            </div>
          )}
        </div>

        {/* Latest revision + next due */}
        <div style={cardStyle}>
          <p style={sectionTitle}>Revizní aktivita</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
              <History size={15} style={{ color: 'var(--text-muted)', marginTop: 2, flexShrink: 0 }} />
              <div>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Poslední revize</div>
                {latestRevision ? (
                  <div style={{ fontSize: '0.9rem', fontWeight: 600 }}>
                    {new Date(latestRevision.performedAt).toLocaleDateString('cs-CZ')}
                    <span style={{ fontWeight: 400, color: 'var(--text-muted)', marginLeft: 6, fontSize: '0.85rem' }}>
                      {latestRevision.revisionTypeName}
                    </span>
                    {latestRevision.resultStatus && latestRevision.resultStatus !== 'planned' && (
                      <span style={{ marginLeft: 6 }}>
                        <Badge variant={RESULT_COLOR[latestRevision.resultStatus] ?? 'muted'}>
                          {RESULT_LABEL[latestRevision.resultStatus] ?? latestRevision.resultStatus}
                        </Badge>
                      </span>
                    )}
                  </div>
                ) : (
                  <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Žádná provedená revize</div>
                )}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
              <CalendarClock size={15} style={{ color: 'var(--text-muted)', marginTop: 2, flexShrink: 0 }} />
              <div>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Příští termín</div>
                {nextDue ? (
                  <div style={{ fontSize: '0.9rem', fontWeight: 600 }}>
                    <span style={{ color: nextDue.daysUntil <= 30 ? 'var(--accent-orange)' : undefined }}>
                      {new Date(nextDue.dueAt).toLocaleDateString('cs-CZ')}
                    </span>
                    <span style={{ fontWeight: 400, color: 'var(--text-muted)', marginLeft: 6, fontSize: '0.85rem' }}>
                      {nextDue.revisionTypeName}
                    </span>
                    <span style={{ marginLeft: 6, fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                      ({nextDue.daysUntil}d)
                    </span>
                  </div>
                ) : (
                  <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>—</div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Recent service records */}
        {asset.serviceRecords && asset.serviceRecords.length > 0 && (
          <div style={cardStyle}>
            <p style={sectionTitle}>Servisní záznamy</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {asset.serviceRecords.slice(0, 5).map((r) => (
                <li key={r.id} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', borderBottom: '1px solid var(--border)', paddingBottom: 4 }}>
                  <span>
                    <Clock size={11} style={{ marginRight: 4, verticalAlign: -1, opacity: 0.5 }} />
                    {new Date(r.date).toLocaleDateString('cs-CZ')} — {r.type}
                  </span>
                  {r.cost !== null && <span style={{ color: 'var(--text-muted)' }}>{r.cost.toLocaleString('cs-CZ')} Kč</span>}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── Field Checks Tab ────────────────────────────────────────────────

function FieldChecksTab({ assetId }: { assetId: string }) {
  const { data, isLoading } = useFieldChecks(assetId)

  if (isLoading) return <LoadingState />

  const checks: FieldCheckItem[] = data?.data ?? []

  if (checks.length === 0) {
    return (
      <div style={{ textAlign: 'center', padding: '40px 0', color: 'var(--text-muted)' }}>
        <CheckCircle size={32} style={{ opacity: 0.3, marginBottom: 12 }} />
        <p style={{ margin: 0 }}>Žádné záznamy o kontrolách</p>
        <p style={{ margin: '6px 0 0', fontSize: '0.85rem' }}>Kontroly se vytvoří při skenování QR kódu zařízení v terénu.</p>
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      {checks.map((check) => (
        <div key={check.id} style={{
          border: '1px solid var(--border)', borderRadius: 10, padding: '12px 16px',
          display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12,
        }}>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 4, flexWrap: 'wrap' }}>
              {check.result && (
                <Badge variant={CHECK_RESULT_COLOR[check.result] ?? 'muted'}>
                  {CHECK_RESULT_LABEL[check.result] ?? check.result}
                </Badge>
              )}
              <Badge variant={CONFIDENCE_COLOR[check.confidenceLevel]}>
                Věrohodnost: {CONFIDENCE_LABEL[check.confidenceLevel]}
              </Badge>
            </div>
            <div style={{ fontSize: '0.83rem', color: 'var(--text-muted)' }}>
              {new Date(check.startedAt).toLocaleString('cs-CZ')}
              {check.user && <> · {check.user.name}</>}
              {check.notes && <div style={{ marginTop: 4 }}>{check.notes}</div>}
            </div>
            {check.signals.length > 0 && (
              <div style={{ display: 'flex', gap: 6, marginTop: 6, flexWrap: 'wrap' }}>
                {check.signals.map((s) => (
                  <span key={s.id} style={{
                    fontSize: '0.75rem', padding: '2px 7px',
                    background: s.isValid !== false ? 'rgba(34,197,94,0.1)' : 'rgba(239,68,68,0.1)',
                    color: s.isValid !== false ? '#16a34a' : '#dc2626',
                    borderRadius: 4,
                  }}>
                    {s.signalType}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}

// ─── Main Page ──────────────────────────────────────────────────────

export default function AssetPassportPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [tab, setTab] = useState('overview')
  const [showFieldCheck, setShowFieldCheck] = useState(false)
  const scanToken = searchParams.get('scanToken')

  const { data: passport, isLoading, error } = useQuery<PassportResponse>({
    queryKey: ['assets', id, 'passport'],
    queryFn: () => apiClient.get(`/assets/${id}/passport`).then((r) => r.data),
    enabled: !!id,
  })

  if (isLoading) return <LoadingState />
  if (error || !passport) return <ErrorState message="Aktivum nenalezeno." />

  const { asset, compliance } = passport
  const hasAssetType = !!asset.assetTypeId

  return (
    <div>
      {/* Header */}
      <div className="page-header" style={{ marginBottom: 16, alignItems: 'flex-start' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
          <Button size="sm" onClick={() => navigate('/assets')}><ArrowLeft size={15} /></Button>
          <div>
            <h1 className="page-title" style={{ marginBottom: 4 }}>{asset.name}</h1>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
              <Badge variant={STATUS_COLOR[asset.status] ?? 'muted'}>{STATUS_LABEL[asset.status] ?? asset.status}</Badge>
              <Badge variant="blue">{CATEGORY_LABEL[asset.category] ?? asset.category}</Badge>
              {asset.assetType && <Badge variant="muted">{asset.assetType.name}</Badge>}
              {!hasAssetType && (
                <Badge variant="muted">Bez typu zařízení</Badge>
              )}
              {asset.serialNumber && (
                <span style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>S/N: {asset.serialNumber}</span>
              )}
              {asset.location && (
                <span style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{asset.location}</span>
              )}
            </div>
          </div>
        </div>
        <ComplianceHeaderBadge status={compliance.status} />
      </div>

      {/* QR scan context banner */}
      {scanToken && (
        <div style={{
          padding: '10px 16px', marginBottom: 12,
          background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.3)', borderRadius: 8,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.88rem', color: '#16a34a' }}>
            <CheckCircle size={15} />
            <span>QR kód naskenován — zařízení ověřeno</span>
          </div>
          <Button size="sm" onClick={() => setShowFieldCheck(true)}>
            Spustit kontrolu
          </Button>
        </div>
      )}

      {/* Overdue banner */}
      <OverdueBanner count={compliance.overduePlans} />

      {/* No-asset-type info */}
      {!hasAssetType && compliance.status === 'not_configured' && (
        <div style={{
          padding: '10px 16px', marginBottom: 16,
          background: 'var(--surface-alt, var(--surface))', border: '1px solid var(--border)', borderRadius: 8,
          fontSize: '0.85rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 8,
        }}>
          <MinusCircle size={15} />
          Zařízení nemá přiřazen typ — automatická synchronizace plánů není k dispozici.
        </div>
      )}

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 4, borderBottom: '1px solid var(--border)', marginBottom: 24 }}>
        {TABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            style={{
              display: 'flex', alignItems: 'center', gap: 6,
              padding: '8px 14px', border: 'none',
              borderBottom: tab === t.id ? '2px solid var(--accent-blue)' : '2px solid transparent',
              background: 'none', cursor: 'pointer', fontSize: '0.88rem',
              fontWeight: tab === t.id ? 700 : 400,
              color: tab === t.id ? 'var(--accent-blue)' : 'var(--text-muted)',
              marginBottom: -1, transition: 'all 0.15s',
            }}
          >
            {t.icon}
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div>
        {tab === 'overview' && <OverviewTab passport={passport} />}
        {tab === 'plans' && <PlansTab assetId={id!} hasAssetType={hasAssetType} />}
        {tab === 'history' && <HistoryTab assetId={id!} />}
        {tab === 'checks' && <FieldChecksTab assetId={id!} />}
        {tab === 'documents' && <DocumentsTab assetId={id!} />}
        {tab === 'audit' && <AuditTab assetId={id!} />}
      </div>

      {/* Field check modal */}
      {showFieldCheck && (
        <Suspense fallback={null}>
          <FieldCheckModal
            assetId={id!}
            assetName={asset.name}
            scanEventId={scanToken ? undefined : undefined}
            onClose={() => setShowFieldCheck(false)}
            onSuccess={() => setTab('checks')}
          />
        </Suspense>
      )}
    </div>
  )
}
