import { Injectable, NotFoundException } from '@nestjs/common'
import { PrismaService } from '../prisma/prisma.service'
import { PropertyScopeService } from '../common/services/property-scope.service'
import type { AuthUser } from '@ifmio/shared-types'

const DAY_MS = 86_400_000
// TODO P7.3: make per-plan using Math.max(plan.reminderDaysBefore, 14)
const DUE_SOON_DAYS = 30

export type AssetComplianceStatus =
  | 'not_configured'
  | 'missing_plan'
  | 'overdue'
  | 'due_soon'
  | 'compliant'

export interface AssetComplianceSummary {
  status: AssetComplianceStatus
  totalPlans: number
  activePlans: number
  overduePlans: number
  dueSoonPlans: number
  missingMandatoryPlans: number
  lastRevisionAt: string | null
  nextDueAt: string | null
}

@Injectable()
export class AssetPassportService {
  constructor(
    private prisma: PrismaService,
    private scope: PropertyScopeService,
  ) {}

  // ─── Passport overview ─────────────────────────────────────────

  async getPassport(user: AuthUser, assetId: string) {
    const asset = await this.prisma.asset.findFirst({
      where: { id: assetId, tenantId: user.tenantId, deletedAt: null },
      include: {
        property: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true } },
        assetType: {
          select: {
            id: true, name: true, code: true,
            _count: { select: { activityAssignments: true } },
            activityAssignments: {
              where: { isRequired: true },
              select: { id: true, revisionTypeId: true },
            },
          },
        },
        serviceRecords: { orderBy: { date: 'desc' }, take: 5 },
      },
    })
    if (!asset) throw new NotFoundException('Aktivum nenalezeno')
    await this.scope.verifyEntityAccess(user, asset.propertyId)

    const now = new Date()
    const dueSoonThreshold = new Date(now.getTime() + DUE_SOON_DAYS * DAY_MS)

    // Fetch all active revision plans for this asset
    const plans = await this.prisma.revisionPlan.findMany({
      where: { assetId, tenantId: user.tenantId, status: 'active' },
      select: {
        id: true, revisionTypeId: true, title: true, nextDueAt: true,
        isMandatory: true, generatedFromAssetType: true, isCustomized: true,
        reminderDaysBefore: true,
        revisionType: { select: { name: true } },
      },
      orderBy: { nextDueAt: 'asc' },
    })

    // plansSummary
    let overdueCount = 0
    let dueSoonCount = 0
    let autoGeneratedCount = 0
    let customizedCount = 0

    for (const p of plans) {
      if (p.generatedFromAssetType) autoGeneratedCount++
      if (p.isCustomized) customizedCount++
      if (!p.nextDueAt) continue
      if (p.nextDueAt < now) overdueCount++
      else if (p.nextDueAt <= dueSoonThreshold) dueSoonCount++
    }

    const plansSummary = {
      total: plans.length,
      autoGenerated: autoGeneratedCount,
      customized: customizedCount,
      overdue: overdueCount,
      dueSoon: dueSoonCount,
    }

    // Compute compliance status (based on mandatory plans)
    const mandatoryPlans = plans.filter((p) => p.isMandatory)
    const existingRevisionTypeIds = new Set(plans.map((p) => p.revisionTypeId))

    // Detect missing mandatory plans
    const requiredAssignments = (asset.assetType as any)?.activityAssignments ?? []
    const missingMandatoryCount = requiredAssignments.filter(
      (a: { revisionTypeId: string }) => !existingRevisionTypeIds.has(a.revisionTypeId),
    ).length

    let complianceStatus: AssetComplianceStatus

    if (!asset.assetTypeId && plans.length === 0) {
      complianceStatus = 'not_configured'
    } else if (missingMandatoryCount > 0) {
      complianceStatus = 'missing_plan'
    } else {
      const overdueMandatory = mandatoryPlans.filter((p) => p.nextDueAt && p.nextDueAt < now)
      const dueSoonMandatory = mandatoryPlans.filter(
        (p) => p.nextDueAt && p.nextDueAt >= now && p.nextDueAt <= dueSoonThreshold,
      )

      if (mandatoryPlans.length === 0 && plans.length > 0) {
        // Has plans but none mandatory — treat non-mandatory plans for compliance
        const overdueAny = plans.filter((p) => p.nextDueAt && p.nextDueAt < now)
        const dueSoonAny = plans.filter(
          (p) => p.nextDueAt && p.nextDueAt >= now && p.nextDueAt <= dueSoonThreshold,
        )
        if (overdueAny.length > 0) complianceStatus = 'overdue'
        else if (dueSoonAny.length > 0) complianceStatus = 'due_soon'
        else complianceStatus = 'compliant'
      } else if (overdueMandatory.length > 0) {
        complianceStatus = 'overdue'
      } else if (dueSoonMandatory.length > 0) {
        complianceStatus = 'due_soon'
      } else if (mandatoryPlans.length > 0) {
        complianceStatus = 'compliant'
      } else {
        complianceStatus = 'not_configured'
      }
    }

    // Latest revision event for this asset
    const latestEvent = await this.prisma.revisionEvent.findFirst({
      where: {
        tenantId: user.tenantId,
        revisionPlan: { assetId },
        // resultStatus has a DB default so is always set; filter out 'planned' (not yet performed)
        resultStatus: { notIn: ['planned'] },
        performedAt: { not: null },
      },
      orderBy: { performedAt: 'desc' },
      select: {
        id: true, performedAt: true, resultStatus: true,
        revisionPlan: {
          select: { revisionType: { select: { name: true } } },
        },
      },
    })

    // Next due plan (soonest upcoming)
    const nextDuePlan = plans.find((p) => p.nextDueAt && p.nextDueAt >= now)

    const compliance: AssetComplianceSummary = {
      status: complianceStatus,
      totalPlans: plans.length,
      activePlans: plans.length,
      overduePlans: overdueCount,
      dueSoonPlans: dueSoonCount,
      missingMandatoryPlans: missingMandatoryCount,
      lastRevisionAt: latestEvent?.performedAt?.toISOString() ?? null,
      nextDueAt: nextDuePlan?.nextDueAt?.toISOString() ?? null,
    }

    const latestRevision = latestEvent
      ? {
          id: latestEvent.id,
          revisionTypeName: latestEvent.revisionPlan.revisionType.name,
          performedAt: latestEvent.performedAt!.toISOString(),
          resultStatus: latestEvent.resultStatus,
        }
      : null

    const nextDue = nextDuePlan
      ? {
          revisionPlanId: nextDuePlan.id,
          revisionTypeName: nextDuePlan.revisionType?.name ?? '',
          dueAt: nextDuePlan.nextDueAt!.toISOString(),
          daysUntil: Math.ceil((nextDuePlan.nextDueAt!.getTime() - now.getTime()) / DAY_MS),
        }
      : null

    // Strip activityAssignments from the response (internal use only)
    const { assetType, ...assetRest } = asset as any
    const assetForResponse = {
      ...assetRest,
      assetType: assetType
        ? {
            id: assetType.id,
            name: assetType.name,
            code: assetType.code,
            _count: assetType._count,
          }
        : null,
    }

    return {
      asset: assetForResponse,
      compliance,
      plansSummary,
      latestRevision,
      nextDue,
    }
  }

  // ─── Revision history ──────────────────────────────────────────

  async getRevisionHistory(
    user: AuthUser,
    assetId: string,
    params: { page?: number; limit?: number } = {},
  ) {
    await this.resolveAsset(user, assetId)

    const page = Math.max(1, params.page ?? 1)
    const limit = Math.min(100, Math.max(1, params.limit ?? 20))
    const skip = (page - 1) * limit

    const where = {
      tenantId: user.tenantId,
      revisionPlan: { assetId },
    }

    const [data, total] = await Promise.all([
      this.prisma.revisionEvent.findMany({
        where,
        orderBy: { performedAt: 'desc' },
        skip,
        take: limit,
        include: {
          revisionPlan: {
            select: {
              id: true, title: true,
              revisionType: { select: { id: true, name: true, code: true } },
            },
          },
        },
      }),
      this.prisma.revisionEvent.count({ where }),
    ])

    return { data, total, page, pageSize: limit, totalPages: Math.ceil(total / limit) }
  }

  // ─── Audit timeline ────────────────────────────────────────────

  async getAuditEvents(
    user: AuthUser,
    assetId: string,
    params: { page?: number; limit?: number } = {},
  ) {
    await this.resolveAsset(user, assetId)

    const page = Math.max(1, params.page ?? 1)
    const limit = Math.min(100, Math.max(1, params.limit ?? 20))
    const skip = (page - 1) * limit

    const where = {
      tenantId: user.tenantId,
      entity: 'Asset',
      entityId: assetId,
    }

    const [data, total] = await Promise.all([
      this.prisma.auditLog.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip,
        take: limit,
        include: {
          user: { select: { id: true, name: true, email: true } },
        },
      }),
      this.prisma.auditLog.count({ where }),
    ])

    return { data, total, page, pageSize: limit, totalPages: Math.ceil(total / limit) }
  }

  // ─── Helpers ───────────────────────────────────────────────────

  private async resolveAsset(user: AuthUser, assetId: string) {
    const asset = await this.prisma.asset.findFirst({
      where: { id: assetId, tenantId: user.tenantId, deletedAt: null },
      select: { id: true, propertyId: true },
    })
    if (!asset) throw new NotFoundException('Aktivum nenalezeno')
    await this.scope.verifyEntityAccess(user, asset.propertyId)
    return asset
  }
}
