-- This migration does not run in a transaction
-- Step 1: Add new PropertyType enum values (must commit before use)
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SVJ';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BD';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'RENTAL_RESIDENTIAL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'RENTAL_MUNICIPAL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'CONDO_NO_SVJ';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'MIXED_USE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SINGLE_FAMILY';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_OFFICE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_RETAIL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_WAREHOUSE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_INDUSTRIAL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'PARKING';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'LAND';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'OTHER';
